import { AICapabilityNotImplementedError } from "../types";

export interface GenerateImageInput {
  prompt: string;
  /** e.g. "1200x630" for a Build in Public card, "1024x1024" for general use. */
  size?: string;
}

export interface GenerateImageOutput {
  url: string;
}

/**
 * Placeholder. No image-generation provider is wired up yet — Build in
 * Public card images are rendered locally with @napi-rs/canvas
 * (src/lib/renderCard.ts), not generated by a model.
 *
 * When an image provider is added: implement it in providers/ behind the
 * same kind of thin adapter as nvidia.ts/anthropic.ts, add a
 * `generateImage` method to whichever provider(s) support it (this is a
 * capability the text AIProvider interface doesn't need to grow to support,
 * since not every provider will implement it), and swap this function's
 * body to call it. The call site in routes/buildInPublic.ts is already
 * structured so that attaching a generated image is an additive change —
 * see the comment there.
 */
export async function generateImage(_input: GenerateImageInput): Promise<GenerateImageOutput> {
  throw new AICapabilityNotImplementedError("image.generateImage");
}
